clearvars;
close all;
% clc;

addpath('commonFunctions', ...
    'continuumClasses', ...
    'coreClasses', ...
    'generatedFiles', ...
    'meshes', ...
    'meshes/abaqus', ...
    'meshes/generalFunctions', ...
    'meshes/meshGenerators', ...
    'scripts', ...
    'scripts/pre', ...
    'scripts/pre/user', ...
    'scripts/pre/user/MarlonFranke/', ...
    'scripts/pre/published/', ...
    'scripts/pre/published/FrankeZaehringerHilleOrtigosaBetschGil2023/', ...
    'scripts/pre/user/FelixZaehringer/', ...
    'scripts/pre/user/JakobHammes/', ...
    'scripts/pre/user/MoritzHille/', ...
    'scripts/post', ...
    'scripts/solver', ...
    'tests', ...
    'externalToolboxes', ...
    'externalToolboxes/tikz3d', ...
    'externalToolboxes/tikz', ...
    'externalToolboxes/tikz/src', ...
    'externalToolboxes/export_fig', ...
    'externalToolboxes/adimat-0.6.6-5529-DebianBuster-x86_64', ...
    'externalToolboxes/MBeautifier', ...
    'externalData', ...
    'externalData/ANN', ...
    'externalData/ANN/solid')

% Set the property only if the graphical version of Matlab is used (not in bash version)
%if usejava('desktop')
%    set(0, 'DefaultFigureWindowStyle', 'docked')
%end

% parpool(24);
