clear all;
close all;
% clc;

addpath('commonFunctions',...
        'continuumClasses',...
        'coreClasses',...
        'generatedFiles',...
        'meshes',...
        'meshes/abaqus',...
        'meshes/meshGenerators',...
        'scripts',...
        'scripts/pre',...
        'scripts/post',...
        'scripts/solver',...
        'tests',...
        'externalToolboxes',...
        'externalToolboxes/tikz3d',...
        'externalToolboxes/tikz',...
        'externalToolboxes/tikz/src',...
        'externalToolboxes/export_fig',...
        'externalToolboxes/adimat-0.6.6-5529-DebianBuster-x86_64',...
        'externalToolboxes/MBeautifier')

% Set the property only if the graphical version of Matlab is used (not in bash version)
if usejava('desktop')
    set(0, 'DefaultFigureWindowStyle', 'docked')
end

% parpool(24);
