# Generated by Robin Pfefferkorn
<<<<<<< HEAD
#include:class-scrartcl,scrreprt,scrbook
#include:amsmath
#include:amssymb
#include:amsthm
#include:babel
#include:biblatex
#include:blindtext
#include:csqoutes
#include:fix-cm
#include:geometry
#include:graphicx
#include:hyperref
#include:lmodern
#include:pgfplots
#include:psfrag
#include:tikz
#include:xcolor
#
#
#usercommands
\headerblock{text_for_right_header}
\kitlogopath{path_to_logo}
\theauthor
\thedate
\thetitle